"""Alembic environment for Nautilus Builder.

Adoption Report §3.4 Phase 1. Uses raw psycopg connections (not SQLAlchemy
ORM) to match the existing repository pattern. Migrations are written as raw
SQL via op.execute(), not ORM-autogenerated models.

The connection URL is resolved from the environment at runtime:
  BUILDER_DATABASE_URL (preferred) or DATABASE_URL.

Example: postgresql://builder_dev_builder@localhost:5432/builder
"""
from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = None  # Raw SQL migrations; no ORM metadata target.


def _get_database_url() -> str:
    url = os.environ.get("BUILDER_DATABASE_URL") or os.environ.get("DATABASE_URL", "")
    if not url:
        raise RuntimeError(
            "Alembic requires BUILDER_DATABASE_URL or DATABASE_URL env var. "
            "Example: postgresql://builder_dev_builder@localhost:5432/builder"
        )
    return url


def run_migrations_offline() -> None:
    """Generate SQL without a live DB connection (for deployment review)."""
    context.configure(
        url=_get_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        version_table="alembic_version",
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live DB connection via psycopg (no ORM engine)."""
    import psycopg

    url = _get_database_url()
    # psycopg 3 connection (synchronous). Autocommit=False so Alembic controls
    # the transaction.
    with psycopg.connect(url) as connection:
        connection.execute("SELECT 1")  # connectivity check
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            version_table="alembic_version",
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
