"""Structural Protocols for repository/service surfaces that have multiple
implementations (in-memory for local/dev, Postgres for production).

Both implementations conform structurally with identical method surfaces.
These Protocols let the FastAPI factory accept either implementation without
losing type safety or resorting to ``# type: ignore``.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from packages.auth import UserProjectContext


@runtime_checkable
class StrategyRepositoryProtocol(Protocol):
    """Strategy repository surface shared by InMemory and Postgres impls."""

    def save(self, spec: Any, *, context: UserProjectContext | None = None) -> dict[str, object]: ...
    def detail(self, strategy_id: str, *, context: UserProjectContext | None = None) -> dict[str, object] | None: ...
    def list(self, *, context: UserProjectContext | None = None) -> list[dict[str, object]]: ...
    def spec_for_version(self, strategy_version_id: str, *, context: UserProjectContext | None = None) -> Any: ...
    def update_draft(self, strategy_id: str, spec: Any, *, context: UserProjectContext | None = None) -> dict[str, object] | None: ...
    def update_status(self, strategy_id: str, new_status: str, *, context: UserProjectContext | None = None) -> dict[str, object] | None: ...
    def create_version(self, strategy_id: str, spec: Any, *, context: UserProjectContext | None = None) -> dict[str, object] | None: ...
    def approve_strategy(self, strategy_id: str, *, context: UserProjectContext | None = None) -> dict[str, object] | None: ...
    def clone_strategy(self, strategy_id: str, *, context: UserProjectContext | None = None) -> dict[str, object] | None: ...
    def save_explicit(self, strategy_id: str, spec: Any, *, context: UserProjectContext | None = None) -> dict[str, object]: ...


@runtime_checkable
class BacktestJobServiceProtocol(Protocol):
    """Backtest job service surface shared by in-memory and Postgres impls."""

    def create_job(self, payload: dict[str, str]) -> Any: ...
    def get_job(self, job_id: str, *, context: UserProjectContext | None = None) -> Any: ...
    def get_latest_job_for_strategy(self, strategy_version_id: str, *, context: UserProjectContext | None = None) -> Any: ...
    def list_jobs_for_strategy(self, strategy_version_id: str, *, context: UserProjectContext | None = None) -> list[Any]: ...
    def record_frontend_disconnect(self, job_id: str) -> Any: ...
    def request_cancel(self, job_id: str, *, context: UserProjectContext | None = None) -> Any: ...
    def transition_job(self, job_id: str, stage: str, *, worker_id: str | None = None, result_artifact_refs: dict[str, str] | None = None, context: UserProjectContext | None = None) -> Any: ...


@runtime_checkable
class WorkflowRepositoryProtocol(Protocol):
    """Workflow repository surface shared by InMemory and Postgres adapter impls."""

    def save_result(self, result: Any) -> None: ...
    def result(self, result_id: str, *, context: UserProjectContext | None = None) -> Any: ...
    def list_results(self, *, limit: int | None = None, offset: int = 0, context: UserProjectContext | None = None) -> list[Any]: ...
    def result_for_job(self, test_job_id: str) -> Any: ...
    def save_job(self, job: Any) -> None: ...
    def job(self, test_job_id: str) -> Any: ...
    def save_strategy(self, strategy: Any) -> None: ...
    def strategy(self, strategy_id: str) -> Any: ...
    def save_version(self, version: Any) -> None: ...
    def version(self, strategy_version_id: str) -> Any: ...
    def suggestions_for_result(self, result_id: str, *, context: UserProjectContext | None = None) -> list[Any]: ...
    def suggestions_for_lineage(self, strategy_lineage_id: str, *, context: UserProjectContext | None = None) -> list[Any]: ...
    def suggestions_for_ai_thread(self, ai_thread_id: str, *, context: UserProjectContext | None = None) -> list[Any]: ...
    def save_ai_suggestion(self, suggestion: Any) -> None: ...
