import { describe, it, expect } from "vitest";
import { buildFreshness } from "./freshness";

/**
 * Phase 5: Strengthen source freshness display.
 * Proves that missing ≠ true_zero and all 7 statuses are distinct.
 */

describe("Freshness — 7 statuses are visually distinct", () => {
  const now = Date.now() * 1_000_000;

  it("live: recent real data", () => {
    const meta = buildFreshness(now - 500_000_000, "websocket", { receiveNs: now });
    expect(meta.source_status).toBe("live");
    expect(meta.stale).toBe(false);
    expect(meta.missing).toBe(false);
    expect(meta.true_zero).toBe(false);
  });

  it("stale: data older than threshold", () => {
    const meta = buildFreshness(now - 10_000_000_000, "websocket", { receiveNs: now });
    expect(meta.source_status).toBe("stale");
    expect(meta.stale).toBe(true);
    expect(meta.missing).toBe(false);
    expect(meta.true_zero).toBe(false);
  });

  it("missing: null timestamp (no data received)", () => {
    const meta = buildFreshness(null, "websocket");
    expect(meta.source_status).toBe("missing");
    expect(meta.missing).toBe(true);
    expect(meta.true_zero).toBe(false);
    expect(meta.source_available).toBe(false);
  });

  it("synthetic: mock/synthetic provenance", () => {
    const meta = buildFreshness(now - 500_000_000, "mock", { receiveNs: now });
    expect(meta.source_status).toBe("synthetic");
    expect(meta.stale).toBe(false);
    expect(meta.missing).toBe(false);
    expect(meta.provenance).toBe("mock");
  });

  it("true_zero: explicitly zero, NOT missing", () => {
    const meta = buildFreshness(now, "websocket", { trueZero: true });
    expect(meta.source_status).toBe("true_zero");
    expect(meta.true_zero).toBe(true);
    expect(meta.missing).toBe(false);
    expect(meta.source_available).toBe(true);
  });

  it("unavailable: source is down", () => {
    const meta = buildFreshness(null, "websocket", { unavailable: true });
    expect(meta.source_status).toBe("unavailable");
    expect(meta.source_available).toBe(false);
    expect(meta.missing).toBe(false);
    expect(meta.true_zero).toBe(false);
  });

  it("HARD RULE: missing is never true_zero and vice versa", () => {
    const missingMeta = buildFreshness(null, "websocket");
    const zeroMeta = buildFreshness(now, "websocket", { trueZero: true });

    expect(missingMeta.missing).toBe(true);
    expect(missingMeta.true_zero).toBe(false);

    expect(zeroMeta.true_zero).toBe(true);
    expect(zeroMeta.missing).toBe(false);

    // Different source_status values
    expect(missingMeta.source_status).not.toBe(zeroMeta.source_status);
  });

  it("all 7 statuses produce distinct source_status values", () => {
    const statuses = new Set<string>();

    statuses.add(buildFreshness(now - 500_000_000, "websocket", { receiveNs: now }).source_status);
    statuses.add(buildFreshness(now - 10_000_000_000, "websocket", { receiveNs: now }).source_status);
    statuses.add(buildFreshness(null, "websocket").source_status);
    statuses.add(buildFreshness(now - 500_000_000, "mock", { receiveNs: now }).source_status);
    statuses.add(buildFreshness(now, "websocket", { trueZero: true }).source_status);
    statuses.add(buildFreshness(null, "websocket", { unavailable: true }).source_status);

    // Should be at least 6 distinct values (unknown is fallback, not generated by buildFreshness)
    expect(statuses.size).toBeGreaterThanOrEqual(6);
  });
});
